In [3]:
import torch
print(torch.tensor([[1,2],[3,4]])) #2차원 형태의 텐서 생성
print(torch.tensor([[1,2], [3,4]], dtype = torch.float64)) #dtype 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [4]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy()) #텐서를 ndarray로 변환

[[1 2]
 [3 4]]


In [5]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) #파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) #인덱스로 접근
print('-----------------------')
print(temp[2:5], temp[4:-1]) #슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
-----------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [6]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w - v)

tensor([2, 2, 3])


In [7]:
temp = torch.tensor([[1,2], [3,4]]) #2*2 행렬 생성
print(temp.shape)
print('-------------------')
print(temp.view(4,1)) #2*2행렬을 4*1로 변형
print('-------------------')
print(temp.view(-1)) #2*2행렬을 1차원 벡터로 변형
print('-------------------')
print(temp.view(1, -1)) #1 * 자동 변형
print('-------------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])
-------------------
tensor([1, 2, 3, 4])
-------------------
tensor([[1, 2, 3, 4]])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])
